Require at least plone.api 1.3.3.
fixes
  Module ftw.contacts.browser.contact, line 22, in get_review_state
TypeError: get_state() got an unexpected keyword argument default